"""Builds the 'Referencias' worksheet."""

from __future__ import annotations

from openpyxl import Workbook
from openpyxl.styles import Font
from openpyxl.utils import get_column_letter

from src.data import REFERENCES
from src.styles import (
    DARK_GREY, GOLD, NAVY, SILVER, THIN_BORDER, WHITE,
    fill, left_align, center,
)


def build_references(wb: Workbook) -> None:
    ws = wb.create_sheet("Referencias")
    ws.sheet_view.showGridLines = False

    for c, w in {1: 24, 2: 72, 3: 14, 4: 50}.items():
        ws.column_dimensions[get_column_letter(c)].width = w

    # Title
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=4)
    t = ws.cell(row=1, column=1, value="📚  References / Fuentes")
    t.font = Font(name="Calibri", size=16, bold=True, color=WHITE)
    t.fill = fill(NAVY)
    t.alignment = left_align()
    ws.row_dimensions[1].height = 28

    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=4)
    sub = ws.cell(
        row=2, column=1,
        value="All data sourced from the following public references as of April 1, 2026.",
    )
    sub.font = Font(name="Calibri", size=9, italic=True, color=DARK_GREY)
    sub.fill = fill(SILVER)
    sub.alignment = left_align()
    ws.row_dimensions[2].height = 16

    row = 3
    for col_off, label in enumerate(["Source", "URL", "Accessed", "Description"]):
        c = ws.cell(row=row, column=1 + col_off, value=label)
        c.font = Font(name="Calibri", size=10, bold=True, color=WHITE)
        c.fill = fill("2F2F2F")
        c.alignment = center()
        c.border = THIN_BORDER
    ws.row_dimensions[row].height = 18
    row += 1

    for i, (source, url, accessed, desc) in enumerate(REFERENCES):
        row_fill = fill("F2F2F2" if i % 2 == 0 else "FFFFFF")
        for col_off, val in enumerate([source, url, accessed, desc]):
            col = 1 + col_off
            c = ws.cell(row=row, column=col, value=val)
            c.font = Font(
                name="Calibri", size=9,
                color="0563C1" if col == 2 else DARK_GREY,
                underline="single" if col == 2 else None,
            )
            c.fill = row_fill
            c.border = THIN_BORDER
            c.alignment = left_align(wrap=(col in (2, 4)))
        ws.row_dimensions[row].height = 32
        row += 1

    row += 1
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=4)
    note = ws.cell(
        row=row, column=1,
        value=(
            "Tournament format: 48 teams · 12 groups of 4 · "
            "Top 2 per group + 8 best 3rd-place finishers → Round of 32 · "
            "104 total matches · June 11 – July 19, 2026 · "
            "Host cities: USA, Canada, Mexico"
        ),
    )
    note.font = Font(name="Calibri", size=9, italic=True, color=DARK_GREY)
    note.fill = fill("FFF9C4")
    note.alignment = left_align(wrap=True)
    note.border = THIN_BORDER
    ws.row_dimensions[row].height = 36

    row += 2
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=4)
    gen = ws.cell(
        row=row, column=1,
        value="Generated by generate_quiniela.py  ·  MIT License",
    )
    gen.font = Font(name="Calibri", size=8, italic=True, color="888888")
    gen.alignment = left_align()
