"""All static tournament data for FIFA World Cup 2026."""

from __future__ import annotations

GROUPS: dict[str, list[str]] = {
    "A": ["Mexico", "South Korea", "South Africa", "Czech Republic"],
    "B": ["Canada", "Switzerland", "Qatar", "Bosnia & Herzegovina"],
    "C": ["Brazil", "Morocco", "Scotland", "Haiti"],
    "D": ["USA", "Australia", "Paraguay", "Turkey"],
    "E": ["Germany", "Ecuador", "Ivory Coast", "Curaçao"],
    "F": ["Netherlands", "Japan", "Tunisia", "Sweden"],
    "G": ["Belgium", "Iran", "Egypt", "New Zealand"],
    "H": ["Spain", "Uruguay", "Cape Verde", "Saudi Arabia"],
    "I": ["France", "Senegal", "Norway", "Iraq"],
    "J": ["Argentina", "Algeria", "Austria", "Jordan"],
    "K": ["Portugal", "Colombia", "Uzbekistan", "DR Congo"],
    "L": ["England", "Croatia", "Panama", "Ghana"],
}

# (matchday, date, time_et, home, away, venue)
GROUP_MATCHES: dict[str, list[tuple]] = {
    "A": [
        (1, "Jun 11", "3 pm ET",  "Mexico",        "South Africa",        "Mexico City"),
        (1, "Jun 11", "10 pm ET", "South Korea",   "Czech Republic",      "Guadalajara"),
        (2, "Jun 18", "12 pm ET", "Czech Republic","South Africa",        "Atlanta"),
        (2, "Jun 18", "9 pm ET",  "Mexico",        "South Korea",         "Guadalajara"),
        (3, "Jun 24", "9 pm ET",  "Czech Republic","Mexico",              "Mexico City"),
        (3, "Jun 24", "9 pm ET",  "South Africa",  "South Korea",         "Monterrey"),
    ],
    "B": [
        (1, "Jun 12", "3 pm ET",  "Canada",              "Bosnia & Herzegovina", "Toronto"),
        (1, "Jun 13", "3 pm ET",  "Qatar",               "Switzerland",          "San Francisco"),
        (2, "Jun 18", "3 pm ET",  "Switzerland",         "Bosnia & Herzegovina", "Los Angeles"),
        (2, "Jun 18", "6 pm ET",  "Canada",              "Qatar",                "Vancouver"),
        (3, "Jun 24", "3 pm ET",  "Canada",              "Switzerland",          "Vancouver"),
        (3, "Jun 24", "3 pm ET",  "Bosnia & Herzegovina","Qatar",                "Seattle"),
    ],
    "C": [
        (1, "Jun 13", "6 pm ET",  "Brazil",   "Morocco",  "New York/NJ"),
        (1, "Jun 13", "9 pm ET",  "Haiti",    "Scotland", "Boston"),
        (2, "Jun 19", "3 pm ET",  "Scotland", "Morocco",  "Boston"),
        (2, "Jun 19", "9 pm ET",  "Brazil",   "Haiti",    "Philadelphia"),
        (3, "Jun 24", "6 pm ET",  "Scotland", "Brazil",   "Miami"),
        (3, "Jun 24", "6 pm ET",  "Morocco",  "Haiti",    "Atlanta"),
    ],
    "D": [
        (1, "Jun 12", "9 pm ET",  "USA",      "Paraguay", "Los Angeles"),
        (1, "Jun 13", "12 am ET", "Australia","Turkey",   "Vancouver"),
        (2, "Jun 19", "3 pm ET",  "USA",      "Australia","Seattle"),
        (2, "Jun 19", "12 am ET", "Turkey",   "Paraguay", "San Francisco"),
        (3, "Jun 25", "10 pm ET", "Turkey",   "USA",      "Los Angeles"),
        (3, "Jun 25", "10 pm ET", "Paraguay", "Australia","San Francisco"),
    ],
    "E": [
        (1, "Jun 14", "1 pm ET",  "Germany",     "Curaçao",     "Houston"),
        (1, "Jun 14", "7 pm ET",  "Ivory Coast", "Ecuador",     "Philadelphia"),
        (2, "Jun 20", "4 pm ET",  "Germany",     "Ivory Coast", "Toronto"),
        (2, "Jun 20", "8 pm ET",  "Ecuador",     "Curaçao",     "Kansas City"),
        (3, "Jun 25", "4 pm ET",  "Ecuador",     "Germany",     "New York/NJ"),
        (3, "Jun 25", "4 pm ET",  "Curaçao",     "Ivory Coast", "Philadelphia"),
    ],
    "F": [
        (1, "Jun 14", "4 pm ET",  "Netherlands","Japan",        "Dallas"),
        (1, "Jun 14", "10 pm ET", "Sweden",     "Tunisia",      "Monterrey"),
        (2, "Jun 20", "1 pm ET",  "Netherlands","Sweden",       "Houston"),
        (2, "Jun 20", "12 am ET", "Tunisia",    "Japan",        "Monterrey"),
        (3, "Jun 25", "7 pm ET",  "Japan",      "Sweden",       "Dallas"),
        (3, "Jun 25", "7 pm ET",  "Tunisia",    "Netherlands",  "Kansas City"),
    ],
    "G": [
        (1, "Jun 15", "3 pm ET",  "Belgium",     "Egypt",       "Seattle"),
        (1, "Jun 15", "9 pm ET",  "Iran",        "New Zealand", "Los Angeles"),
        (2, "Jun 21", "3 pm ET",  "Belgium",     "Iran",        "Los Angeles"),
        (2, "Jun 21", "9 pm ET",  "New Zealand", "Egypt",       "Vancouver"),
        (3, "Jun 26", "11 pm ET", "Egypt",       "Iran",        "Seattle"),
        (3, "Jun 26", "11 pm ET", "New Zealand", "Belgium",     "Vancouver"),
    ],
    "H": [
        (1, "Jun 15", "12 pm ET", "Spain",        "Cape Verde",   "Atlanta"),
        (1, "Jun 15", "6 pm ET",  "Saudi Arabia", "Uruguay",      "Miami"),
        (2, "Jun 21", "12 pm ET", "Spain",        "Saudi Arabia", "Atlanta"),
        (2, "Jun 21", "6 pm ET",  "Uruguay",      "Cape Verde",   "Miami"),
        (3, "Jun 26", "8 pm ET",  "Cape Verde",   "Saudi Arabia", "Houston"),
        (3, "Jun 26", "8 pm ET",  "Uruguay",      "Spain",        "Guadalajara"),
    ],
    "I": [
        (1, "Jun 16", "3 pm ET",  "France",  "Senegal", "New York/NJ"),
        (1, "Jun 16", "6 pm ET",  "Iraq",    "Norway",  "Boston"),
        (2, "Jun 22", "5 pm ET",  "France",  "Iraq",    "Philadelphia"),
        (2, "Jun 22", "8 pm ET",  "Norway",  "Senegal", "New York/NJ"),
        (3, "Jun 26", "3 pm ET",  "Norway",  "France",  "Boston"),
        (3, "Jun 26", "3 pm ET",  "Senegal", "Iraq",    "Toronto"),
    ],
    "J": [
        (1, "Jun 16", "9 pm ET",  "Argentina","Algeria",   "Kansas City"),
        (1, "Jun 16", "12 am ET", "Austria",  "Jordan",    "San Francisco"),
        (2, "Jun 22", "1 pm ET",  "Argentina","Austria",   "Dallas"),
        (2, "Jun 22", "11 pm ET", "Jordan",   "Algeria",   "San Francisco"),
        (3, "Jun 27", "10 pm ET", "Algeria",  "Austria",   "Kansas City"),
        (3, "Jun 27", "10 pm ET", "Jordan",   "Argentina", "Dallas"),
    ],
    "K": [
        (1, "Jun 17", "1 pm ET",    "Portugal",  "DR Congo",  "Houston"),
        (1, "Jun 17", "10 pm ET",   "Uzbekistan","Colombia",  "Mexico City"),
        (2, "Jun 23", "1 pm ET",    "Portugal",  "Uzbekistan","Houston"),
        (2, "Jun 23", "10 pm ET",   "DR Congo",  "Colombia",  "Guadalajara"),
        (3, "Jun 27", "7:30 pm ET", "Colombia",  "Portugal",  "Miami"),
        (3, "Jun 27", "7:30 pm ET", "DR Congo",  "Uzbekistan","Atlanta"),
    ],
    "L": [
        (1, "Jun 17", "4 pm ET", "England", "Croatia", "Dallas"),
        (1, "Jun 17", "7 pm ET", "Ghana",   "Panama",  "Toronto"),
        (2, "Jun 23", "4 pm ET", "England", "Ghana",   "Boston"),
        (2, "Jun 23", "7 pm ET", "Panama",  "Croatia", "Toronto"),
        (3, "Jun 27", "5 pm ET", "Panama",  "England", "New York/NJ"),
        (3, "Jun 27", "5 pm ET", "Croatia", "Ghana",   "Philadelphia"),
    ],
}

# Round of 32 matchups.
# team_l and team_r are either "GROUP_RANK" strings (resolved at runtime
# to formulas) or "3rd:1X" codes (auto-resolved via the Terceros helper
# sheet to the best-third-place qualifier that faces group X's winner).
R32_LEFT: list[tuple] = [
    ("A2",    "B2",    "Jun 28", "Los Angeles"),
    ("C1",    "F2",    "Jun 29", "Houston"),
    ("E1",    "3rd:1E","Jun 29", "Boston"),
    ("F1",    "C2",    "Jun 29", "Monterrey"),
    ("E2",    "I2",    "Jun 30", "Dallas"),
    ("I1",    "3rd:1I","Jun 30", "New York/NJ"),
    ("A1",    "3rd:1A","Jun 30", "Mexico City"),
    ("L1",    "3rd:1L","Jul 1",  "Atlanta"),
]
R32_RIGHT: list[tuple] = [
    ("G1",    "3rd:1G","Jul 1",  "Seattle"),
    ("D1",    "3rd:1D","Jul 1",  "San Francisco"),
    ("H1",    "J2",    "Jul 2",  "Los Angeles"),
    ("K2",    "L2",    "Jul 2",  "Toronto"),
    ("B1",    "3rd:1B","Jul 2",  "Vancouver"),
    ("D2",    "G2",    "Jul 3",  "Dallas"),
    ("J1",    "H2",    "Jul 3",  "Miami"),
    ("K1",    "3rd:1K","Jul 3",  "Kansas City"),
]

R16_LEFT: list[tuple] = [
    (0, 1,  "Jul 4", "Houston"),       # winners of R32-L[0] and R32-L[1]
    (2, 3,  "Jul 4", "Philadelphia"),
    (4, 5,  "Jul 5", "New York/NJ"),
    (6, 7,  "Jul 5", "Mexico City"),
]
R16_RIGHT: list[tuple] = [
    (0, 1,  "Jul 6", "Dallas"),        # winners of R32-R[0] and R32-R[1]
    (2, 3,  "Jul 6", "Seattle"),
    (4, 5,  "Jul 7", "Atlanta"),
    (6, 7,  "Jul 7", "Vancouver"),
]

QF_LEFT: list[tuple] = [
    (0, 1,  "Jul 9",  "Boston"),       # winners of R16-L[0] and R16-L[1]
    (2, 3,  "Jul 10", "Los Angeles"),
]
QF_RIGHT: list[tuple] = [
    (0, 1,  "Jul 11", "Miami"),
    (2, 3,  "Jul 11", "Kansas City"),
]

SF_LEFT  = (0, 1, "Jul 14", "Dallas")
SF_RIGHT = (0, 1, "Jul 15", "Atlanta")

FINAL    = ("Jul 19", "New York/NJ · MetLife Stadium")
THIRD    = ("Jul 18", "Miami")

GROUP_POWER: dict[str, int] = {
    "A": 1, "B": 2, "C": 4, "D": 8, "E": 16, "F": 32,
    "G": 64, "H": 128, "I": 256, "J": 512, "K": 1024, "L": 2048,
}

# FIFA Annex C — 495 possible third-place matchup combinations.
# Each tuple: (combination_key, vs_1A, vs_1B, vs_1D, vs_1E, vs_1G, vs_1I, vs_1K, vs_1L)
# combination_key = sum of GROUP_POWER values for the 8 qualifying groups.
# vs_1X = group letter whose third-place team faces group X's winner.
THIRD_PLACE_SLOT_ORDER = ("1A", "1B", "1D", "1E", "1G", "1I", "1K", "1L")

THIRD_PLACE_COMBINATIONS: list[tuple[int, str, str, str, str, str, str, str, str]] = [
    (4080, "E", "J", "I", "F", "H", "G", "L", "K"),
    (4072, "H", "G", "I", "D", "J", "F", "L", "K"),
    (4056, "E", "J", "I", "D", "H", "G", "L", "K"),
    (4024, "E", "J", "I", "D", "H", "F", "L", "K"),
    (3960, "E", "G", "I", "D", "J", "F", "L", "K"),
    (3832, "E", "G", "J", "D", "H", "F", "L", "K"),
    (3576, "E", "G", "I", "D", "H", "F", "L", "K"),
    (3064, "E", "G", "J", "D", "H", "F", "L", "I"),
    (2040, "E", "G", "J", "D", "H", "F", "I", "K"),
    (4068, "H", "G", "I", "C", "J", "F", "L", "K"),
    (4052, "E", "J", "I", "C", "H", "G", "L", "K"),
    (4020, "E", "J", "I", "C", "H", "F", "L", "K"),
    (3956, "E", "G", "I", "C", "J", "F", "L", "K"),
    (3828, "E", "G", "J", "C", "H", "F", "L", "K"),
    (3572, "E", "G", "I", "C", "H", "F", "L", "K"),
    (3060, "E", "G", "J", "C", "H", "F", "L", "I"),
    (2036, "E", "G", "J", "C", "H", "F", "I", "K"),
    (4044, "H", "G", "I", "C", "J", "D", "L", "K"),
    (4012, "C", "J", "I", "D", "H", "F", "L", "K"),
    (3948, "C", "G", "I", "D", "J", "F", "L", "K"),
    (3820, "C", "G", "J", "D", "H", "F", "L", "K"),
    (3564, "C", "G", "I", "D", "H", "F", "L", "K"),
    (3052, "C", "G", "J", "D", "H", "F", "L", "I"),
    (2028, "C", "G", "J", "D", "H", "F", "I", "K"),
    (3996, "E", "J", "I", "C", "H", "D", "L", "K"),
    (3932, "E", "G", "I", "C", "J", "D", "L", "K"),
    (3804, "E", "G", "J", "C", "H", "D", "L", "K"),
    (3548, "E", "G", "I", "C", "H", "D", "L", "K"),
    (3036, "E", "G", "J", "C", "H", "D", "L", "I"),
    (2012, "E", "G", "J", "C", "H", "D", "I", "K"),
    (3900, "C", "J", "E", "D", "I", "F", "L", "K"),
    (3772, "C", "J", "E", "D", "H", "F", "L", "K"),
    (3516, "C", "E", "I", "D", "H", "F", "L", "K"),
    (3004, "C", "J", "E", "D", "H", "F", "L", "I"),
    (1980, "C", "J", "E", "D", "H", "F", "I", "K"),
    (3708, "C", "G", "E", "D", "J", "F", "L", "K"),
    (3452, "C", "G", "E", "D", "I", "F", "L", "K"),
    (2940, "C", "G", "E", "D", "J", "F", "L", "I"),
    (1916, "C", "G", "E", "D", "J", "F", "I", "K"),
    (3324, "C", "G", "E", "D", "H", "F", "L", "K"),
    (2812, "C", "G", "J", "D", "H", "F", "L", "E"),
    (1788, "C", "G", "J", "D", "H", "F", "E", "K"),
    (2556, "C", "G", "E", "D", "H", "F", "L", "I"),
    (1532, "C", "G", "E", "D", "H", "F", "I", "K"),
    (1020, "C", "G", "J", "D", "H", "F", "E", "I"),
    (4066, "H", "J", "B", "F", "I", "G", "L", "K"),
    (4050, "E", "J", "I", "B", "H", "G", "L", "K"),
    (4018, "E", "J", "B", "F", "I", "H", "L", "K"),
    (3954, "E", "J", "B", "F", "I", "G", "L", "K"),
    (3826, "E", "J", "B", "F", "H", "G", "L", "K"),
    (3570, "E", "G", "B", "F", "I", "H", "L", "K"),
    (3058, "E", "J", "B", "F", "H", "G", "L", "I"),
    (2034, "E", "J", "B", "F", "H", "G", "I", "K"),
    (4042, "H", "J", "B", "D", "I", "G", "L", "K"),
    (4010, "H", "J", "B", "D", "I", "F", "L", "K"),
    (3946, "I", "G", "B", "D", "J", "F", "L", "K"),
    (3818, "H", "G", "B", "D", "J", "F", "L", "K"),
    (3562, "H", "G", "B", "D", "I", "F", "L", "K"),
    (3050, "H", "G", "B", "D", "J", "F", "L", "I"),
    (2026, "H", "G", "B", "D", "J", "F", "I", "K"),
    (3994, "E", "J", "B", "D", "I", "H", "L", "K"),
    (3930, "E", "J", "B", "D", "I", "G", "L", "K"),
    (3802, "E", "J", "B", "D", "H", "G", "L", "K"),
    (3546, "E", "G", "B", "D", "I", "H", "L", "K"),
    (3034, "E", "J", "B", "D", "H", "G", "L", "I"),
    (2010, "E", "J", "B", "D", "H", "G", "I", "K"),
    (3898, "E", "J", "B", "D", "I", "F", "L", "K"),
    (3770, "E", "J", "B", "D", "H", "F", "L", "K"),
    (3514, "E", "I", "B", "D", "H", "F", "L", "K"),
    (3002, "E", "J", "B", "D", "H", "F", "L", "I"),
    (1978, "E", "J", "B", "D", "H", "F", "I", "K"),
    (3706, "E", "G", "B", "D", "J", "F", "L", "K"),
    (3450, "E", "G", "B", "D", "I", "F", "L", "K"),
    (2938, "E", "G", "B", "D", "J", "F", "L", "I"),
    (1914, "E", "G", "B", "D", "J", "F", "I", "K"),
    (3322, "E", "G", "B", "D", "H", "F", "L", "K"),
    (2810, "H", "G", "B", "D", "J", "F", "L", "E"),
    (1786, "H", "G", "B", "D", "J", "F", "E", "K"),
    (2554, "E", "G", "B", "D", "H", "F", "L", "I"),
    (1530, "E", "G", "B", "D", "H", "F", "I", "K"),
    (1018, "H", "G", "B", "D", "J", "F", "E", "I"),
    (4038, "H", "J", "B", "C", "I", "G", "L", "K"),
    (4006, "H", "J", "B", "C", "I", "F", "L", "K"),
    (3942, "I", "G", "B", "C", "J", "F", "L", "K"),
    (3814, "H", "G", "B", "C", "J", "F", "L", "K"),
    (3558, "H", "G", "B", "C", "I", "F", "L", "K"),
    (3046, "H", "G", "B", "C", "J", "F", "L", "I"),
    (2022, "H", "G", "B", "C", "J", "F", "I", "K"),
    (3990, "E", "J", "B", "C", "I", "H", "L", "K"),
    (3926, "E", "J", "B", "C", "I", "G", "L", "K"),
    (3798, "E", "J", "B", "C", "H", "G", "L", "K"),
    (3542, "E", "G", "B", "C", "I", "H", "L", "K"),
    (3030, "E", "J", "B", "C", "H", "G", "L", "I"),
    (2006, "E", "J", "B", "C", "H", "G", "I", "K"),
    (3894, "E", "J", "B", "C", "I", "F", "L", "K"),
    (3766, "E", "J", "B", "C", "H", "F", "L", "K"),
    (3510, "E", "I", "B", "C", "H", "F", "L", "K"),
    (2998, "E", "J", "B", "C", "H", "F", "L", "I"),
    (1974, "E", "J", "B", "C", "H", "F", "I", "K"),
    (3702, "E", "G", "B", "C", "J", "F", "L", "K"),
    (3446, "E", "G", "B", "C", "I", "F", "L", "K"),
    (2934, "E", "G", "B", "C", "J", "F", "L", "I"),
    (1910, "E", "G", "B", "C", "J", "F", "I", "K"),
    (3318, "E", "G", "B", "C", "H", "F", "L", "K"),
    (2806, "H", "G", "B", "C", "J", "F", "L", "E"),
    (1782, "H", "G", "B", "C", "J", "F", "E", "K"),
    (2550, "E", "G", "B", "C", "H", "F", "L", "I"),
    (1526, "E", "G", "B", "C", "H", "F", "I", "K"),
    (1014, "H", "G", "B", "C", "J", "F", "E", "I"),
    (3982, "H", "J", "B", "C", "I", "D", "L", "K"),
    (3918, "I", "G", "B", "C", "J", "D", "L", "K"),
    (3790, "H", "G", "B", "C", "J", "D", "L", "K"),
    (3534, "H", "G", "B", "C", "I", "D", "L", "K"),
    (3022, "H", "G", "B", "C", "J", "D", "L", "I"),
    (1998, "H", "G", "B", "C", "J", "D", "I", "K"),
    (3886, "C", "J", "B", "D", "I", "F", "L", "K"),
    (3758, "C", "J", "B", "D", "H", "F", "L", "K"),
    (3502, "C", "I", "B", "D", "H", "F", "L", "K"),
    (2990, "C", "J", "B", "D", "H", "F", "L", "I"),
    (1966, "C", "J", "B", "D", "H", "F", "I", "K"),
    (3694, "C", "G", "B", "D", "J", "F", "L", "K"),
    (3438, "C", "G", "B", "D", "I", "F", "L", "K"),
    (2926, "C", "G", "B", "D", "J", "F", "L", "I"),
    (1902, "C", "G", "B", "D", "J", "F", "I", "K"),
    (3310, "C", "G", "B", "D", "H", "F", "L", "K"),
    (2798, "C", "G", "B", "D", "H", "F", "L", "J"),
    (1774, "H", "G", "B", "C", "J", "F", "D", "K"),
    (2542, "C", "G", "B", "D", "H", "F", "L", "I"),
    (1518, "C", "G", "B", "D", "H", "F", "I", "K"),
    (1006, "H", "G", "B", "C", "J", "F", "D", "I"),
    (3870, "E", "J", "B", "C", "I", "D", "L", "K"),
    (3742, "E", "J", "B", "C", "H", "D", "L", "K"),
    (3486, "E", "I", "B", "C", "H", "D", "L", "K"),
    (2974, "E", "J", "B", "C", "H", "D", "L", "I"),
    (1950, "E", "J", "B", "C", "H", "D", "I", "K"),
    (3678, "E", "G", "B", "C", "J", "D", "L", "K"),
    (3422, "E", "G", "B", "C", "I", "D", "L", "K"),
    (2910, "E", "G", "B", "C", "J", "D", "L", "I"),
    (1886, "E", "G", "B", "C", "J", "D", "I", "K"),
    (3294, "E", "G", "B", "C", "H", "D", "L", "K"),
    (2782, "H", "G", "B", "C", "J", "D", "L", "E"),
    (1758, "H", "G", "B", "C", "J", "D", "E", "K"),
    (2526, "E", "G", "B", "C", "H", "D", "L", "I"),
    (1502, "E", "G", "B", "C", "H", "D", "I", "K"),
    (990, "H", "G", "B", "C", "J", "D", "E", "I"),
    (3646, "C", "J", "B", "D", "E", "F", "L", "K"),
    (3390, "C", "E", "B", "D", "I", "F", "L", "K"),
    (2878, "C", "J", "B", "D", "E", "F", "L", "I"),
    (1854, "C", "J", "B", "D", "E", "F", "I", "K"),
    (3262, "C", "E", "B", "D", "H", "F", "L", "K"),
    (2750, "C", "J", "B", "D", "H", "F", "L", "E"),
    (1726, "C", "J", "B", "D", "H", "F", "E", "K"),
    (2494, "C", "E", "B", "D", "H", "F", "L", "I"),
    (1470, "C", "E", "B", "D", "H", "F", "I", "K"),
    (958, "C", "J", "B", "D", "H", "F", "E", "I"),
    (3198, "C", "G", "B", "D", "E", "F", "L", "K"),
    (2686, "C", "G", "B", "D", "J", "F", "L", "E"),
    (1662, "C", "G", "B", "D", "J", "F", "E", "K"),
    (2430, "C", "G", "B", "D", "E", "F", "L", "I"),
    (1406, "C", "G", "B", "D", "E", "F", "I", "K"),
    (894, "C", "G", "B", "D", "J", "F", "E", "I"),
    (2302, "C", "G", "B", "D", "H", "F", "L", "E"),
    (1278, "C", "G", "B", "D", "H", "F", "E", "K"),
    (766, "H", "G", "B", "C", "J", "F", "D", "E"),
    (510, "C", "G", "B", "D", "H", "F", "E", "I"),
    (4065, "H", "J", "I", "F", "A", "G", "L", "K"),
    (4049, "E", "J", "I", "A", "H", "G", "L", "K"),
    (4017, "E", "J", "I", "F", "A", "H", "L", "K"),
    (3953, "E", "J", "I", "F", "A", "G", "L", "K"),
    (3825, "E", "G", "J", "F", "A", "H", "L", "K"),
    (3569, "E", "G", "I", "F", "A", "H", "L", "K"),
    (3057, "E", "G", "J", "F", "A", "H", "L", "I"),
    (2033, "E", "G", "J", "F", "A", "H", "I", "K"),
    (4041, "H", "J", "I", "D", "A", "G", "L", "K"),
    (4009, "H", "J", "I", "D", "A", "F", "L", "K"),
    (3945, "I", "G", "J", "D", "A", "F", "L", "K"),
    (3817, "H", "G", "J", "D", "A", "F", "L", "K"),
    (3561, "H", "G", "I", "D", "A", "F", "L", "K"),
    (3049, "H", "G", "J", "D", "A", "F", "L", "I"),
    (2025, "H", "G", "J", "D", "A", "F", "I", "K"),
    (3993, "E", "J", "I", "D", "A", "H", "L", "K"),
    (3929, "E", "J", "I", "D", "A", "G", "L", "K"),
    (3801, "E", "G", "J", "D", "A", "H", "L", "K"),
    (3545, "E", "G", "I", "D", "A", "H", "L", "K"),
    (3033, "E", "G", "J", "D", "A", "H", "L", "I"),
    (2009, "E", "G", "J", "D", "A", "H", "I", "K"),
    (3897, "E", "J", "I", "D", "A", "F", "L", "K"),
    (3769, "H", "J", "E", "D", "A", "F", "L", "K"),
    (3513, "H", "E", "I", "D", "A", "F", "L", "K"),
    (3001, "H", "J", "E", "D", "A", "F", "L", "I"),
    (1977, "H", "J", "E", "D", "A", "F", "I", "K"),
    (3705, "E", "G", "J", "D", "A", "F", "L", "K"),
    (3449, "E", "G", "I", "D", "A", "F", "L", "K"),
    (2937, "E", "G", "J", "D", "A", "F", "L", "I"),
    (1913, "E", "G", "J", "D", "A", "F", "I", "K"),
    (3321, "H", "G", "E", "D", "A", "F", "L", "K"),
    (2809, "H", "G", "J", "D", "A", "F", "L", "E"),
    (1785, "H", "G", "J", "D", "A", "F", "E", "K"),
    (2553, "H", "G", "E", "D", "A", "F", "L", "I"),
    (1529, "H", "G", "E", "D", "A", "F", "I", "K"),
    (1017, "H", "G", "J", "D", "A", "F", "E", "I"),
    (4037, "H", "J", "I", "C", "A", "G", "L", "K"),
    (4005, "H", "J", "I", "C", "A", "F", "L", "K"),
    (3941, "I", "G", "J", "C", "A", "F", "L", "K"),
    (3813, "H", "G", "J", "C", "A", "F", "L", "K"),
    (3557, "H", "G", "I", "C", "A", "F", "L", "K"),
    (3045, "H", "G", "J", "C", "A", "F", "L", "I"),
    (2021, "H", "G", "J", "C", "A", "F", "I", "K"),
    (3989, "E", "J", "I", "C", "A", "H", "L", "K"),
    (3925, "E", "J", "I", "C", "A", "G", "L", "K"),
    (3797, "E", "G", "J", "C", "A", "H", "L", "K"),
    (3541, "E", "G", "I", "C", "A", "H", "L", "K"),
    (3029, "E", "G", "J", "C", "A", "H", "L", "I"),
    (2005, "E", "G", "J", "C", "A", "H", "I", "K"),
    (3893, "E", "J", "I", "C", "A", "F", "L", "K"),
    (3765, "H", "J", "E", "C", "A", "F", "L", "K"),
    (3509, "H", "E", "I", "C", "A", "F", "L", "K"),
    (2997, "H", "J", "E", "C", "A", "F", "L", "I"),
    (1973, "H", "J", "E", "C", "A", "F", "I", "K"),
    (3701, "E", "G", "J", "C", "A", "F", "L", "K"),
    (3445, "E", "G", "I", "C", "A", "F", "L", "K"),
    (2933, "E", "G", "J", "C", "A", "F", "L", "I"),
    (1909, "E", "G", "J", "C", "A", "F", "I", "K"),
    (3317, "H", "G", "E", "C", "A", "F", "L", "K"),
    (2805, "H", "G", "J", "C", "A", "F", "L", "E"),
    (1781, "H", "G", "J", "C", "A", "F", "E", "K"),
    (2549, "H", "G", "E", "C", "A", "F", "L", "I"),
    (1525, "H", "G", "E", "C", "A", "F", "I", "K"),
    (1013, "H", "G", "J", "C", "A", "F", "E", "I"),
    (3981, "H", "J", "I", "C", "A", "D", "L", "K"),
    (3917, "I", "G", "J", "C", "A", "D", "L", "K"),
    (3789, "H", "G", "J", "C", "A", "D", "L", "K"),
    (3533, "H", "G", "I", "C", "A", "D", "L", "K"),
    (3021, "H", "G", "J", "C", "A", "D", "L", "I"),
    (1997, "H", "G", "J", "C", "A", "D", "I", "K"),
    (3885, "C", "J", "I", "D", "A", "F", "L", "K"),
    (3757, "H", "J", "F", "C", "A", "D", "L", "K"),
    (3501, "H", "F", "I", "C", "A", "D", "L", "K"),
    (2989, "H", "J", "F", "C", "A", "D", "L", "I"),
    (1965, "H", "J", "F", "C", "A", "D", "I", "K"),
    (3693, "C", "G", "J", "D", "A", "F", "L", "K"),
    (3437, "C", "G", "I", "D", "A", "F", "L", "K"),
    (2925, "C", "G", "J", "D", "A", "F", "L", "I"),
    (1901, "C", "G", "J", "D", "A", "F", "I", "K"),
    (3309, "H", "G", "F", "C", "A", "D", "L", "K"),
    (2797, "C", "G", "J", "D", "A", "F", "L", "H"),
    (1773, "H", "G", "J", "C", "A", "F", "D", "K"),
    (2541, "H", "G", "F", "C", "A", "D", "L", "I"),
    (1517, "H", "G", "F", "C", "A", "D", "I", "K"),
    (1005, "H", "G", "J", "C", "A", "F", "D", "I"),
    (3869, "E", "J", "I", "C", "A", "D", "L", "K"),
    (3741, "H", "J", "E", "C", "A", "D", "L", "K"),
    (3485, "H", "E", "I", "C", "A", "D", "L", "K"),
    (2973, "H", "J", "E", "C", "A", "D", "L", "I"),
    (1949, "H", "J", "E", "C", "A", "D", "I", "K"),
    (3677, "E", "G", "J", "C", "A", "D", "L", "K"),
    (3421, "E", "G", "I", "C", "A", "D", "L", "K"),
    (2909, "E", "G", "J", "C", "A", "D", "L", "I"),
    (1885, "E", "G", "J", "C", "A", "D", "I", "K"),
    (3293, "H", "G", "E", "C", "A", "D", "L", "K"),
    (2781, "H", "G", "J", "C", "A", "D", "L", "E"),
    (1757, "H", "G", "J", "C", "A", "D", "E", "K"),
    (2525, "H", "G", "E", "C", "A", "D", "L", "I"),
    (1501, "H", "G", "E", "C", "A", "D", "I", "K"),
    (989, "H", "G", "J", "C", "A", "D", "E", "I"),
    (3645, "C", "J", "E", "D", "A", "F", "L", "K"),
    (3389, "C", "E", "I", "D", "A", "F", "L", "K"),
    (2877, "C", "J", "E", "D", "A", "F", "L", "I"),
    (1853, "C", "J", "E", "D", "A", "F", "I", "K"),
    (3261, "H", "E", "F", "C", "A", "D", "L", "K"),
    (2749, "H", "J", "F", "C", "A", "D", "L", "E"),
    (1725, "H", "J", "E", "C", "A", "F", "D", "K"),
    (2493, "H", "E", "F", "C", "A", "D", "L", "I"),
    (1469, "H", "E", "F", "C", "A", "D", "I", "K"),
    (957, "H", "J", "E", "C", "A", "F", "D", "I"),
    (3197, "C", "G", "E", "D", "A", "F", "L", "K"),
    (2685, "C", "G", "J", "D", "A", "F", "L", "E"),
    (1661, "C", "G", "J", "D", "A", "F", "E", "K"),
    (2429, "C", "G", "E", "D", "A", "F", "L", "I"),
    (1405, "C", "G", "E", "D", "A", "F", "I", "K"),
    (893, "C", "G", "J", "D", "A", "F", "E", "I"),
    (2301, "H", "G", "F", "C", "A", "D", "L", "E"),
    (1277, "H", "G", "E", "C", "A", "F", "D", "K"),
    (765, "H", "G", "J", "C", "A", "F", "D", "E"),
    (509, "H", "G", "E", "C", "A", "F", "D", "I"),
    (4035, "H", "J", "B", "A", "I", "G", "L", "K"),
    (4003, "H", "J", "B", "A", "I", "F", "L", "K"),
    (3939, "I", "J", "B", "F", "A", "G", "L", "K"),
    (3811, "H", "J", "B", "F", "A", "G", "L", "K"),
    (3555, "H", "G", "B", "A", "I", "F", "L", "K"),
    (3043, "H", "J", "B", "F", "A", "G", "L", "I"),
    (2019, "H", "J", "B", "F", "A", "G", "I", "K"),
    (3987, "E", "J", "B", "A", "I", "H", "L", "K"),
    (3923, "E", "J", "B", "A", "I", "G", "L", "K"),
    (3795, "E", "J", "B", "A", "H", "G", "L", "K"),
    (3539, "E", "G", "B", "A", "I", "H", "L", "K"),
    (3027, "E", "J", "B", "A", "H", "G", "L", "I"),
    (2003, "E", "J", "B", "A", "H", "G", "I", "K"),
    (3891, "E", "J", "B", "A", "I", "F", "L", "K"),
    (3763, "E", "J", "B", "F", "A", "H", "L", "K"),
    (3507, "E", "I", "B", "F", "A", "H", "L", "K"),
    (2995, "E", "J", "B", "F", "A", "H", "L", "I"),
    (1971, "E", "J", "B", "F", "A", "H", "I", "K"),
    (3699, "E", "J", "B", "F", "A", "G", "L", "K"),
    (3443, "E", "G", "B", "A", "I", "F", "L", "K"),
    (2931, "E", "J", "B", "F", "A", "G", "L", "I"),
    (1907, "E", "J", "B", "F", "A", "G", "I", "K"),
    (3315, "E", "G", "B", "F", "A", "H", "L", "K"),
    (2803, "H", "J", "B", "F", "A", "G", "L", "E"),
    (1779, "H", "J", "B", "F", "A", "G", "E", "K"),
    (2547, "E", "G", "B", "F", "A", "H", "L", "I"),
    (1523, "E", "G", "B", "F", "A", "H", "I", "K"),
    (1011, "H", "J", "B", "F", "A", "G", "E", "I"),
    (3979, "I", "J", "B", "D", "A", "H", "L", "K"),
    (3915, "I", "J", "B", "D", "A", "G", "L", "K"),
    (3787, "H", "J", "B", "D", "A", "G", "L", "K"),
    (3531, "I", "G", "B", "D", "A", "H", "L", "K"),
    (3019, "H", "J", "B", "D", "A", "G", "L", "I"),
    (1995, "H", "J", "B", "D", "A", "G", "I", "K"),
    (3883, "I", "J", "B", "D", "A", "F", "L", "K"),
    (3755, "H", "J", "B", "D", "A", "F", "L", "K"),
    (3499, "H", "I", "B", "D", "A", "F", "L", "K"),
    (2987, "H", "J", "B", "D", "A", "F", "L", "I"),
    (1963, "H", "J", "B", "D", "A", "F", "I", "K"),
    (3691, "F", "J", "B", "D", "A", "G", "L", "K"),
    (3435, "I", "G", "B", "D", "A", "F", "L", "K"),
    (2923, "F", "J", "B", "D", "A", "G", "L", "I"),
    (1899, "F", "J", "B", "D", "A", "G", "I", "K"),
    (3307, "H", "G", "B", "D", "A", "F", "L", "K"),
    (2795, "H", "G", "B", "D", "A", "F", "L", "J"),
    (1771, "H", "G", "B", "D", "A", "F", "J", "K"),
    (2539, "H", "G", "B", "D", "A", "F", "L", "I"),
    (1515, "H", "G", "B", "D", "A", "F", "I", "K"),
    (1003, "H", "G", "B", "D", "A", "F", "I", "J"),
    (3867, "E", "J", "B", "A", "I", "D", "L", "K"),
    (3739, "E", "J", "B", "D", "A", "H", "L", "K"),
    (3483, "E", "I", "B", "D", "A", "H", "L", "K"),
    (2971, "E", "J", "B", "D", "A", "H", "L", "I"),
    (1947, "E", "J", "B", "D", "A", "H", "I", "K"),
    (3675, "E", "J", "B", "D", "A", "G", "L", "K"),
    (3419, "E", "G", "B", "A", "I", "D", "L", "K"),
    (2907, "E", "J", "B", "D", "A", "G", "L", "I"),
    (1883, "E", "J", "B", "D", "A", "G", "I", "K"),
    (3291, "E", "G", "B", "D", "A", "H", "L", "K"),
    (2779, "H", "J", "B", "D", "A", "G", "L", "E"),
    (1755, "H", "J", "B", "D", "A", "G", "E", "K"),
    (2523, "E", "G", "B", "D", "A", "H", "L", "I"),
    (1499, "E", "G", "B", "D", "A", "H", "I", "K"),
    (987, "H", "J", "B", "D", "A", "G", "E", "I"),
    (3643, "E", "J", "B", "D", "A", "F", "L", "K"),
    (3387, "E", "I", "B", "D", "A", "F", "L", "K"),
    (2875, "E", "J", "B", "D", "A", "F", "L", "I"),
    (1851, "E", "J", "B", "D", "A", "F", "I", "K"),
    (3259, "H", "E", "B", "D", "A", "F", "L", "K"),
    (2747, "H", "J", "B", "D", "A", "F", "L", "E"),
    (1723, "H", "J", "B", "D", "A", "F", "E", "K"),
    (2491, "H", "E", "B", "D", "A", "F", "L", "I"),
    (1467, "H", "E", "B", "D", "A", "F", "I", "K"),
    (955, "H", "J", "B", "D", "A", "F", "E", "I"),
    (3195, "E", "G", "B", "D", "A", "F", "L", "K"),
    (2683, "E", "G", "B", "D", "A", "F", "L", "J"),
    (1659, "E", "G", "B", "D", "A", "F", "J", "K"),
    (2427, "E", "G", "B", "D", "A", "F", "L", "I"),
    (1403, "E", "G", "B", "D", "A", "F", "I", "K"),
    (891, "E", "G", "B", "D", "A", "F", "I", "J"),
    (2299, "H", "G", "B", "D", "A", "F", "L", "E"),
    (1275, "H", "G", "B", "D", "A", "F", "E", "K"),
    (763, "H", "G", "B", "D", "A", "F", "E", "J"),
    (507, "H", "G", "B", "D", "A", "F", "E", "I"),
    (3975, "I", "J", "B", "C", "A", "H", "L", "K"),
    (3911, "I", "J", "B", "C", "A", "G", "L", "K"),
    (3783, "H", "J", "B", "C", "A", "G", "L", "K"),
    (3527, "I", "G", "B", "C", "A", "H", "L", "K"),
    (3015, "H", "J", "B", "C", "A", "G", "L", "I"),
    (1991, "H", "J", "B", "C", "A", "G", "I", "K"),
    (3879, "I", "J", "B", "C", "A", "F", "L", "K"),
    (3751, "H", "J", "B", "C", "A", "F", "L", "K"),
    (3495, "H", "I", "B", "C", "A", "F", "L", "K"),
    (2983, "H", "J", "B", "C", "A", "F", "L", "I"),
    (1959, "H", "J", "B", "C", "A", "F", "I", "K"),
    (3687, "C", "J", "B", "F", "A", "G", "L", "K"),
    (3431, "I", "G", "B", "C", "A", "F", "L", "K"),
    (2919, "C", "J", "B", "F", "A", "G", "L", "I"),
    (1895, "C", "J", "B", "F", "A", "G", "I", "K"),
    (3303, "H", "G", "B", "C", "A", "F", "L", "K"),
    (2791, "H", "G", "B", "C", "A", "F", "L", "J"),
    (1767, "H", "G", "B", "C", "A", "F", "J", "K"),
    (2535, "H", "G", "B", "C", "A", "F", "L", "I"),
    (1511, "H", "G", "B", "C", "A", "F", "I", "K"),
    (999, "H", "G", "B", "C", "A", "F", "I", "J"),
    (3863, "E", "J", "B", "A", "I", "C", "L", "K"),
    (3735, "E", "J", "B", "C", "A", "H", "L", "K"),
    (3479, "E", "I", "B", "C", "A", "H", "L", "K"),
    (2967, "E", "J", "B", "C", "A", "H", "L", "I"),
    (1943, "E", "J", "B", "C", "A", "H", "I", "K"),
    (3671, "E", "J", "B", "C", "A", "G", "L", "K"),
    (3415, "E", "G", "B", "A", "I", "C", "L", "K"),
    (2903, "E", "J", "B", "C", "A", "G", "L", "I"),
    (1879, "E", "J", "B", "C", "A", "G", "I", "K"),
    (3287, "E", "G", "B", "C", "A", "H", "L", "K"),
    (2775, "H", "J", "B", "C", "A", "G", "L", "E"),
    (1751, "H", "J", "B", "C", "A", "G", "E", "K"),
    (2519, "E", "G", "B", "C", "A", "H", "L", "I"),
    (1495, "E", "G", "B", "C", "A", "H", "I", "K"),
    (983, "H", "J", "B", "C", "A", "G", "E", "I"),
    (3639, "E", "J", "B", "C", "A", "F", "L", "K"),
    (3383, "E", "I", "B", "C", "A", "F", "L", "K"),
    (2871, "E", "J", "B", "C", "A", "F", "L", "I"),
    (1847, "E", "J", "B", "C", "A", "F", "I", "K"),
    (3255, "H", "E", "B", "C", "A", "F", "L", "K"),
    (2743, "H", "J", "B", "C", "A", "F", "L", "E"),
    (1719, "H", "J", "B", "C", "A", "F", "E", "K"),
    (2487, "H", "E", "B", "C", "A", "F", "L", "I"),
    (1463, "H", "E", "B", "C", "A", "F", "I", "K"),
    (951, "H", "J", "B", "C", "A", "F", "E", "I"),
    (3191, "E", "G", "B", "C", "A", "F", "L", "K"),
    (2679, "E", "G", "B", "C", "A", "F", "L", "J"),
    (1655, "E", "G", "B", "C", "A", "F", "J", "K"),
    (2423, "E", "G", "B", "C", "A", "F", "L", "I"),
    (1399, "E", "G", "B", "C", "A", "F", "I", "K"),
    (887, "E", "G", "B", "C", "A", "F", "I", "J"),
    (2295, "H", "G", "B", "C", "A", "F", "L", "E"),
    (1271, "H", "G", "B", "C", "A", "F", "E", "K"),
    (759, "H", "G", "B", "C", "A", "F", "E", "J"),
    (503, "H", "G", "B", "C", "A", "F", "E", "I"),
    (3855, "I", "J", "B", "C", "A", "D", "L", "K"),
    (3727, "H", "J", "B", "C", "A", "D", "L", "K"),
    (3471, "H", "I", "B", "C", "A", "D", "L", "K"),
    (2959, "H", "J", "B", "C", "A", "D", "L", "I"),
    (1935, "H", "J", "B", "C", "A", "D", "I", "K"),
    (3663, "C", "J", "B", "D", "A", "G", "L", "K"),
    (3407, "I", "G", "B", "C", "A", "D", "L", "K"),
    (2895, "C", "J", "B", "D", "A", "G", "L", "I"),
    (1871, "C", "J", "B", "D", "A", "G", "I", "K"),
    (3279, "H", "G", "B", "C", "A", "D", "L", "K"),
    (2767, "H", "G", "B", "C", "A", "D", "L", "J"),
    (1743, "H", "G", "B", "C", "A", "D", "J", "K"),
    (2511, "H", "G", "B", "C", "A", "D", "L", "I"),
    (1487, "H", "G", "B", "C", "A", "D", "I", "K"),
    (975, "H", "G", "B", "C", "A", "D", "I", "J"),
    (3631, "C", "J", "B", "D", "A", "F", "L", "K"),
    (3375, "C", "I", "B", "D", "A", "F", "L", "K"),
    (2863, "C", "J", "B", "D", "A", "F", "L", "I"),
    (1839, "C", "J", "B", "D", "A", "F", "I", "K"),
    (3247, "H", "F", "B", "C", "A", "D", "L", "K"),
    (2735, "C", "J", "B", "D", "A", "F", "L", "H"),
    (1711, "H", "J", "B", "C", "A", "F", "D", "K"),
    (2479, "H", "F", "B", "C", "A", "D", "L", "I"),
    (1455, "H", "F", "B", "C", "A", "D", "I", "K"),
    (943, "H", "J", "B", "C", "A", "F", "D", "I"),
    (3183, "C", "G", "B", "D", "A", "F", "L", "K"),
    (2671, "C", "G", "B", "D", "A", "F", "L", "J"),
    (1647, "C", "G", "B", "D", "A", "F", "J", "K"),
    (2415, "C", "G", "B", "D", "A", "F", "L", "I"),
    (1391, "C", "G", "B", "D", "A", "F", "I", "K"),
    (879, "C", "G", "B", "D", "A", "F", "I", "J"),
    (2287, "C", "G", "B", "D", "A", "F", "L", "H"),
    (1263, "H", "G", "B", "C", "A", "F", "D", "K"),
    (751, "H", "G", "B", "C", "A", "F", "D", "J"),
    (495, "H", "G", "B", "C", "A", "F", "D", "I"),
    (3615, "E", "J", "B", "C", "A", "D", "L", "K"),
    (3359, "E", "I", "B", "C", "A", "D", "L", "K"),
    (2847, "E", "J", "B", "C", "A", "D", "L", "I"),
    (1823, "E", "J", "B", "C", "A", "D", "I", "K"),
    (3231, "H", "E", "B", "C", "A", "D", "L", "K"),
    (2719, "H", "J", "B", "C", "A", "D", "L", "E"),
    (1695, "H", "J", "B", "C", "A", "D", "E", "K"),
    (2463, "H", "E", "B", "C", "A", "D", "L", "I"),
    (1439, "H", "E", "B", "C", "A", "D", "I", "K"),
    (927, "H", "J", "B", "C", "A", "D", "E", "I"),
    (3167, "E", "G", "B", "C", "A", "D", "L", "K"),
    (2655, "E", "G", "B", "C", "A", "D", "L", "J"),
    (1631, "E", "G", "B", "C", "A", "D", "J", "K"),
    (2399, "E", "G", "B", "C", "A", "D", "L", "I"),
    (1375, "E", "G", "B", "C", "A", "D", "I", "K"),
    (863, "E", "G", "B", "C", "A", "D", "I", "J"),
    (2271, "H", "G", "B", "C", "A", "D", "L", "E"),
    (1247, "H", "G", "B", "C", "A", "D", "E", "K"),
    (735, "H", "G", "B", "C", "A", "D", "E", "J"),
    (479, "H", "G", "B", "C", "A", "D", "E", "I"),
    (3135, "C", "E", "B", "D", "A", "F", "L", "K"),
    (2623, "C", "J", "B", "D", "A", "F", "L", "E"),
    (1599, "C", "J", "B", "D", "A", "F", "E", "K"),
    (2367, "C", "E", "B", "D", "A", "F", "L", "I"),
    (1343, "C", "E", "B", "D", "A", "F", "I", "K"),
    (831, "C", "J", "B", "D", "A", "F", "E", "I"),
    (2239, "H", "F", "B", "C", "A", "D", "L", "E"),
    (1215, "H", "E", "B", "C", "A", "F", "D", "K"),
    (703, "H", "J", "B", "C", "A", "F", "D", "E"),
    (447, "H", "E", "B", "C", "A", "F", "D", "I"),
    (2175, "C", "G", "B", "D", "A", "F", "L", "E"),
    (1151, "C", "G", "B", "D", "A", "F", "E", "K"),
    (639, "C", "G", "B", "D", "A", "F", "E", "J"),
    (383, "C", "G", "B", "D", "A", "F", "E", "I"),
    (255, "H", "G", "B", "C", "A", "F", "D", "E"),
]

REFERENCES = [
    (
        "FIFA Official",
        "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026"
        "/articles/match-schedule-fixtures-results-teams-stadiums",
        "Apr 1, 2026",
        "Official match schedule and fixtures",
    ),
    (
        "FOX Sports",
        "https://www.foxsports.com/stories/soccer/"
        "2026-world-cup-schedule-all-games-dates-matchups-how-watch",
        "Apr 1, 2026",
        "Full broadcast schedule with dates, times and venues",
    ),
    (
        "CNN Español",
        "https://cnnespanol.cnn.com/2026/04/01/deportes/"
        "grupos-zonas-copa-mundial-2026-orix",
        "Apr 1, 2026",
        "Complete groups and match calendar (post-playoff)",
    ),
    (
        "Marca",
        "https://www.marca.com/futbol/mundial/2026/04/01/"
        "estan-12-grupos-completos-mundial-falta-irak-bolivia.html",
        "Apr 1, 2026",
        "12 complete groups confirmed; Iraq & DR Congo qualify via inter-confederation playoff",
    ),
    (
        "Wikipedia – 2026 FIFA World Cup",
        "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup",
        "Apr 1, 2026",
        "Tournament overview, format, host cities, qualification",
    ),
]
